name: Deployment
on:
  workflow_dispatch:
  schedule:
    # Run daily at 1:00 AM UTC
    - cron: "0 1 * * *"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: krcg.org
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: uv sync
      - name: Build static files
        run: LOCAL_CARDS=1 uv run krcg-static build
      - name: Setup SSH key
        run: |
          mkdir /home/runner/.ssh
          echo "${{ secrets.KRCG_DEPLOY_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          echo "${{ secrets.KRCG_GRA_HOST_ID }}" > /home/runner/.ssh/known_hosts
          echo "${{ secrets.KRCG_SBG_HOST_ID }}" >> /home/runner/.ssh/known_hosts
      - name: Deploy files to krcg-sbg
        run: rsync -rlptq --delete-after -e ssh build/ lpanhaleux@51.178.45.139:projects/static.krcg.org/dist
