name: Deployment
on: [workflow_dispatch]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: krcg.org
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Build static files
        run: krcg-static build
      - name: Setup SSH key
        run: |
          mkdir /home/runner/.ssh
          echo "${{ secrets.KRCG_DEPLOY_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          echo "${{ secrets.KRCG_GRA_HOST_ID }}" > /home/runner/.ssh/known_hosts
          echo "${{ secrets.KRCG_SBG_HOST_ID }}" >> /home/runner/.ssh/known_hosts
      - name: Deploy files to krcg-gra
        run: rsync -rlptq --delete-after -e ssh build/ lpanhaleux@152.228.170.51:projects/static.krcg.org/dist
      - name: Deploy files to krcg-sbg
        run: rsync -rlptq --delete-after -e ssh build/ lpanhaleux@51.178.45.139:projects/static.krcg.org/dist
